name: Generate Resume PDF
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Generate PDF
        run: |
          npm run build
          npm run preview
          ping http://localhost:4173 -c 5

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
